root-project/rootspi

jenkins/jk-all

Set the home directory for slc6 and centos7 to avoid dealing with afs and kerb tickets with ccache on PRs.

Set HOME for slc and centos7 PRs

---

jenkins/jk-setup.sh

If there is a typo, or a missing env variable, the build process continues although it fails loading the externals. This patch stops the build at this step, exiting with status code 1.

Stop build if externals don't receive correct params

---

jenkins/jk-all
jenkins/logparser-rules/ROOT-incremental-LogParserRules.txt

This PR enables providing a flag to jk-all for selecting if the build process should either compile or test. If no extra flag is supplied, the build process will first build then run tests. Example:
`jk-all build` : Builds
`jk-all test` : Runs tests
`jk-all` : Builds, then tests
The log parser rules has also been moved to a subdirectory under jenkins/logparser-rules.

Pipeline support

---

jenkins/jk-setup.sh

AFS is deprecated and we should use cvmfs instead.

Get clang from cvmfs instead of afs

---

jenkins/jk-setup.sh

The nightlies only build -opt builds. Relying on the platform name makes the build fail for debug and other builds.
Follow up PR for #11

Always use opt llvm builds

---

jenkins/root-build.cmake

In order to specify the c++-version on an axis in Jenkins, it has to be enabled through an environment variable instead of through the extra cmake flags. This PR provides this through the environment variable `CXX_VERSION`.

Specify c++-version through environment variable

---

jenkins/getPlatform.py

CernVM uses Scientific Linux naming (also for RHEL 7 compatible).

Add support for CernVM VMs

---

jenkins/getPlatform.py

On Fedora 26 the command 'gcc -dumpversion' returns '7', instead of '7.x.y'.
This does not match the regular expression currenty used to parse out the gcc
version. This patch fixes this.

getPlatform.py: add support for new format in 'gcc -dumpversion'

---

docker/ubuntu16-base/Dockerfile
docker/ubuntu16/Dockerfile
docker/ubuntu16/build.sh

This PR adds support for building ROOT in a Docker container that is pushed to Dockerhub. The script that initializes this is [DockerDeployUbuntu.groovy](https://github.com/root-project/jenkins-pipelines/blob/master/DockerDeployUbuntu.groovy). The two jobs set up for it on Jenkins is [root-docker-snapshot](https://epsft-jenkins.cern.ch/view/ROOT/job/root-docker-snapshot/) and [root-docker-6-10-patches](https://epsft-jenkins.cern.ch/view/ROOT/job/root-docker-v6-10-00-patches/).

Add support for Ubuntu 16.04 Docker distribution

---

docker/ubuntu16/Dockerfile

The PATH is no longer needed to be set after ROOT is installed to /usr/local/. The LD_LIBRARY_PATH is also updated to correspond to the right location of library files.

Don't add PATH and set correct LD_LIBRARY_PATH in container

---

docker/ubuntu16/build.sh

Otherwise containers will try and touch the file /workspace

Add correct workspace

---

docker/ubuntu16/build.sh

Otherwise we get permission errors that /ccache/tmp cannot be created while building

sftnight must own /ccache

---

jenkins/root-test.cmake

We want to think big but start small: we do not want to run by default the
benchmarking infrastructure yet. We will have a separate job dedicate for it at
first.

Prepare our infrastructure for gbenchmarks. Do not run them by default.

---

docker/ubuntu16/Dockerfile

`ROOT.py` is in `/usr/local/lib/root`, not in `/usr/local/lib`

Fix PYTHONPATH

---

jenkins/jk-setup.sh

Otherwise we get warnings about libtinfo: clang++: /lib64/libtinfo.so.5: no version information available (it is breaking a lot of references in tests)

Clang build on Ubuntu can be used on Ubuntu and not centos7

---

jenkins/root-build.cmake

Pythia8 can't be enabled on Windows node..
14:19:34 -- Looking for Pythia8
14:19:37 -- Could NOT find Pythia8 (missing: PYTHIA8_INCLUDE_DIR PYTHIA8_LIBRARY) 
14:19:37 CMake Error at cmake/modules/SearchInstalledSoftware.cmake:670 (message):
14:19:37   Pythia8 libraries not found and they are required (pythia8 option enabled)
14:19:37 Call Stack (most recent call first):
14:19:37   CMakeLists.txt:165 (include)
This reverts commit bf524ba3147339f3bbf2be67fbbb7c77bff8b327.

Revert "Re-add Pythia8 to all supported modules configuration setup"

---

jenkins/root-build.cmake

Adds the variables to veto the jupyter based tests, see the PR to roottest here: https://github.com/root-project/roottest/pull/507

add envvar to veto tests of jupyter with py2 on mac os

---

jenkins/root-build.cmake

Only test `io_uring` features on the Fedora 32 node (see discussion on the main build system PR here: https://github.com/root-project/root/pull/5919#discussion_r462186345)
**Edit:** switched from explicit enable to explicit disable in commit 0ca38b6, i.e. 
```cmake
if(uring AND NOT DEFINED ENV{ROOTTEST_IGNORE_URING})
ROOT_ADD_GTEST(RIoUring RIoUring.cxx LIBRARIES RIO uring)
endif()
```
Instead of the first approach: 
```cmake
if(uring AND DEFINED ENV{ROOTTEST_ENABLE_URING})
ROOT_ADD_GTEST(RIoUring RIoUring.cxx LIBRARIES RIO uring)
endif()
```
which had the disadvantage of forcing the uring feature developer to define `ROOTTEST_ENABLE_URING` if the development environment was not `fedora32`.

only enable io_uring tests on Fedora 32

---

jenkins/root-build.cmake

We cannot install llvmlite required by numba because there are not yet
any binaries and building the wheel locally also fails.

[python][macos] veto numba for mac10beta

---

jenkins/root-build.cmake

This flag will be used in the tests of the new ROOT.RDF.Distributed layer on top of RDataFrame, those which require pyspark to run.

Introduce ROOTTEST_IGNORE_PYSPARK_PY* variables

---

jenkins/root-build.cmake

Seems that without this "-" sign the label isn't picked correctly so the variable is not written to the file:
```
sftnight@pcepsft10:~/build/workspace/root-pullrequests-build/build$ cat CTestEnvVars.cmake 
set(ENV{ROOTTEST_IGNORE_URING} TRUE)
set(ENV{ROOTTEST_IGNORE_NUMBA_PY2} TRUE)
sftnight@pcepsft10:~/build/workspace/root-pullrequests-build/build$ hostname
pcepsft10
```

Small typo in i386 label

---

jenkins/root-build.cmake

These variables are no longer needed since the introduction of the dataframe_distributed_pyspark build option.
Through that option we can decide on which machines the distributed RDataFrame spark tests should be run.

Revert creation of ROOTTEST_IGNORE_PYSPARK_PY* variables

---

ui5bld/build.sh

JSROOT will not provide jQuery, therefore normal ui5 library will be required

build openui5 with jquery

---

jenkins/root-build.cmake

The goal of these changes is to test the assumption that the following errors on the release build of MacOS12:
https://lcgapp-services.cern.ch/root-jenkins/view/Releases/job/root-release-master/BUILDTYPE=Release,LABEL=mac12,V=master/690/parsed_console/
are due to the differences in the CMake PyROOT options with respect to the MacOS12 nightly builds:
https://lcgapp-services.cern.ch/root-jenkins/view/ROOT%20Nightly/job/root-nightly-master/LABEL=mac12,SPEC=soversion,V=master/3076/consoleFull
which build just fine.
In particular, the main suspect is the setting of `PYTHON_EXECUTABLE`, but also `pyroot3` is set to `On` to have the same options as in the nightlies.

Make sure the PyROOT options of MacOS12 release builds are the same as in the nightlies

---

jenkins/root-build.cmake

Because it is not possible at the moment to install numba with
pip on macOS12 on ARM.
https://github.com/numba/llvmlite/issues/693
https://github.com/numba/llvmlite/issues/799
I tried to install pandas and numpy on macphsft26 (macOS12 ARM) with the XCode Python and there were no issues, so I'm not disabling pandas on mac12arm as it is done with mac11arm and mac10beta.

Disable Python3 Numba tests also on macOS12 ARM

---

jenkins/root-build.cmake

This PR readjusts some settings that were done to test the XCode Python3 on macOS12.
Now we want to test and release with the XCode Python3 on macOS11 and 12, starting from v6.26.

Since 6.26, we release with XCode Python3 on MacOS11&12

---

rdoc/makedoxy.sh

No need to define PYTHON and PYTHON_EXECUTABLE in this script. It is already defined in  the Makefile of the ROOT reference guide.

Un-define PYTHON

---

jenkins/root-build.cmake

The test for PR root-project/root#10301 because the tests disable all options not explicitly listed as supported, even if the default for the option is that it is enabled. This PR adds the new option introduced by that PR to the list of options known by the test.

Add builtin_gtest option

---

jenkins/jk-all.bat

Windows CI builds often reports errors even though the build was successful. The reason for this is that the CI script dumps the environment variables in the log, and one of the environment variables contains the description of the PR that is being tested. If the description quotes the error that the PR is fixing (which is a reasonable thing to do), this means that because the PR description contains an error message, the CI build log will contain this error message and when the log is scanned the build will be flagged as a failure even though the error did not happen during the build.
The script dumps the environment twice. The first time the PR description is filtered out, but the second time not. This PR copies the filtering done the first time (line 53) to also be used the second time …

Don't report a windows build as failed when a PR description quotes the error the PR is fixing
